# Generated by Django 6.0.4 on 2026-04-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('transmission', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('km', models.CharField(blank=True, max_length=100, null=True)),
                ('mileage', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('img', models.URLField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
