# Generated by Django 6.0.4 on 2026-04-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_offer_created_at_offer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
