# Generated by Django 6.0.4 on 2026-04-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_offer_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='is_seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
