# Generated by Django 6.0.4 on 2026-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
