# Generated by Django 6.0.4 on 2026-05-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_offer_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
