# Generated by Django 6.0.4 on 2026-05-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_offer_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
