# Generated by Django 6.0.4 on 2026-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_scraperstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperstatus',
            name='force_scrape',
            field=models.BooleanField(default=False),
        ),
    ]
