# Generated by Django 6.0.4 on 2026-05-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_scraperstatus_force_scrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
