# Generated by Django 6.0.4 on 2026-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_offer_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperstatus',
            name='last_maintenance_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
