# Generated by Django 6.0.4 on 2026-05-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_scraperstatus_last_maintenance_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='is_archived',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_favorite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
