# Generated by Django 6.0.4 on 2026-05-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_alter_offer_is_archived_alter_offer_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='telegram_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
